// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {booklet} from '../models';

export function OpenFolder(arg1:string):Promise<void>;

export function ProcessBooklet(arg1:booklet.Options):Promise<string>;

export function SelectFile():Promise<string>;

export function SelectSaveFile(arg1:string):Promise<string>;

export function ShowSuccessDialog(arg1:string):Promise<string>;
