// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function ProcessBooklet(arg1) {
  return window['go']['main']['App']['ProcessBooklet'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectSaveFile(arg1) {
  return window['go']['main']['App']['SelectSaveFile'](arg1);
}

export function ShowSuccessDialog(arg1) {
  return window['go']['main']['App']['ShowSuccessDialog'](arg1);
}
