// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFolder(arg1) {
  return ObfuscatedCall(0, [arg1]);
}

export function ProcessBooklet(arg1) {
  return ObfuscatedCall(1, [arg1]);
}

export function SelectFile() {
  return ObfuscatedCall(2, []);
}

export function SelectSaveFile() {
  return ObfuscatedCall(3, []);
}

export function ShowSuccessDialog(arg1) {
  return ObfuscatedCall(4, [arg1]);
}
